name: filenames
version: 0.1.0.0
github: bartoszluka/filenames
description: GUI for creating repetetive filenames
homepage: https://github.com/bartoszluka/filenames
license: BSD3
author: Bartosz Łuka
maintainer: bartoszluka1@gmail.com
copyright: 2023 Bartosz Łuka
category: GUI

extra-source-files:
  - README.md

default-extensions:
  - OverloadedStrings

dependencies:
  - base >= 4.7 && < 5
  - data-default
  - lens
  - monomer
  - text
  - text-show
  - composition
  - time
  - relude

executables:
  filenames:
    source-dirs: src
    main: Main.hs
    ghc-options:
      - -fwarn-incomplete-patterns
      - -threaded
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
